name: Build and Deploy to github & gitee & algolia
on:
  # 手动触发
  # workflow_dispatch:
  # 推送main分支触发
  push:
    branches:
      - main
jobs:
  # 部署和发版
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 构建Node环境
      - name: '构建node环境'
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # 检出main分支代码
      - name: '检查代码'
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      # 安装依赖
      - name: '安装依赖'
        run: npm install

      # 项目打包
      - name: '项目打包'
        run: npm run build

      # github 部署分支gh-pages 到github pages
      - name: '部署dist到gh-pages分支'
        uses: JamesIves/github-pages-deploy-action@4.2.0
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch: gh-pages
          folder: dist

      # 同步github代码到gitee
      - name: '同步到gitee'
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:quyuandong/my-tools.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:qyd_9/my-tools.git

      # 自动部署gitee gh-pages分支
      - name: '部署至gitee的gh-pages'
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: 1984602738@qq.com
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: qyd_9/my-tools
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: gh-pages
